// The building blocks of an invitation: optional detail modules and questions
// to ask the guest. Occasions (occasions.js) pre-fill a sensible set of both.

export const MODULES = [
  { id: 'dress', icon: '👗', label: 'What to wear', type: 'chips',
    options: ['Casual', 'Smart casual', 'Dressy', 'Formal / black tie', 'Costume encouraged', 'Comfy & cozy', 'Outdoor-ready', 'Wear something you love'],
    placeholder: 'e.g. Dressy — something black & velvet' },
  { id: 'colors', icon: '🎨', label: 'Color palette', type: 'chips',
    options: ['Black & orange', 'Earth tones', 'All white', 'Pastels', 'Jewel tones', 'Anything sparkly'],
    placeholder: 'e.g. Autumn tones — rust, gold, forest green' },
  { id: 'bring', icon: '🎒', label: 'What to bring', type: 'chips',
    options: ['Just yourself', 'A blanket', 'A dish to share', 'Water bottle', 'A warm layer', 'Swimsuit & towel', 'Your ID', 'An offering for the altar'],
    placeholder: 'e.g. A warm layer and your sense of wonder' },
  { id: 'food', icon: '🍽️', label: 'Food & drink', type: 'chips',
    options: ['Dinner included', 'Snacks provided', 'Potluck', 'Drinks provided', 'Eat beforehand', 'Dessert on me'],
    placeholder: 'e.g. Three courses + mulled cider' },
  { id: 'cost', icon: '💸', label: 'Cost', type: 'chips',
    options: ['My treat ✨', 'Let’s split it', 'Totally free', 'Tickets are covered'],
    placeholder: 'e.g. About $20 each' },
  { id: 'transport', icon: '🚗', label: 'Getting there', type: 'chips',
    options: ['I’ll pick you up', 'Meet me there', 'Let’s ride together', 'Rideshare’s on me', 'Walking distance'],
    placeholder: 'e.g. I’ll pick you up at 6:30' },
  { id: 'parking', icon: '🅿️', label: 'Parking', type: 'chips',
    options: ['Free lot on site', 'Street parking', 'Valet', 'Skip the car'],
    placeholder: 'e.g. Free lot behind the building' },
  { id: 'weather', icon: '🌦️', label: 'Weather & terrain', type: 'chips',
    options: ['Indoors', 'Mostly outdoors', 'Might get muddy', 'Could be chilly — bring layers', 'Sunny — bring shades'],
    placeholder: 'e.g. Outdoors by the fire — it gets cold' },
  { id: 'activity', icon: '🥾', label: 'Activity level', type: 'chips',
    options: ['Totally chill', 'A little walking', 'Moderate', 'Active — wear sneakers'] },
  { id: 'vibe', icon: '✨', label: 'The vibe', type: 'chips',
    options: ['Low-key', 'Romantic', 'Playful', 'Fancy', 'Spooky', 'Adventurous', 'Witchy'] },
  { id: 'surprise', icon: '🎁', label: 'Surprise level', type: 'chips',
    options: ['No surprises', 'A little mystery', 'Total surprise — trust me'] },
  { id: 'guests', icon: '👯', label: 'Who’s coming', type: 'chips',
    options: ['Just us two', 'Bring a friend', 'Small group', 'Bring the whole coven'] },
  { id: 'kidspets', icon: '🐾', label: 'Kids & pets', type: 'chips',
    options: ['Pet-friendly', 'Kid-friendly', 'Adults only'] },
  { id: 'access', icon: '♿', label: 'Accessibility', type: 'text',
    placeholder: 'e.g. Step-free entrance, plenty of seating' },
  { id: 'link', icon: '🔗', label: 'Link', type: 'link',
    placeholder: 'https://… (tickets, menu, playlist)' },
  { id: 'notes', icon: '📝', label: 'Good to know', type: 'textarea',
    placeholder: 'Anything else — the secret password, which door, etc.' },
  { id: 'rsvpby', icon: '⏳', label: 'Please reply by', type: 'date' },
];
export const MODULE_BY_ID = Object.fromEntries(MODULES.map(m => [m.id, m]));

export const QUESTIONS = [
  { id: 'diet', q: 'Any allergies or food preferences?' },
  { id: 'drink', q: 'Drink of choice?' },
  { id: 'song', q: 'A song request for the night?' },
  { id: 'pickup', q: 'Where should I pick you up?' },
  { id: 'wish', q: 'Anything that would make it perfect?' },
];
export const QUESTION_BY_ID = Object.fromEntries(QUESTIONS.map(q => [q.id, q]));
