// The building blocks of an invitation: optional detail modules, questions to
// ask the guest, and occasion templates that pre-fill a sensible set of both.

export const MODULES = [
  { id: 'dress', icon: '👗', label: 'What to wear', type: 'chips',
    options: ['Casual', 'Smart casual', 'Dressy', 'Formal / black tie', 'Costume encouraged', 'Comfy & cozy', 'Outdoor-ready', 'Wear something you love'],
    placeholder: 'e.g. Dressy — something black & velvet' },
  { id: 'colors', icon: '🎨', label: 'Color palette', type: 'chips',
    options: ['Black & orange', 'Earth tones', 'All white', 'Pastels', 'Jewel tones', 'Anything sparkly'],
    placeholder: 'e.g. Autumn tones — rust, gold, forest green' },
  { id: 'bring', icon: '🎒', label: 'What to bring', type: 'chips',
    options: ['Just yourself', 'A blanket', 'A dish to share', 'Water bottle', 'A warm layer', 'Swimsuit & towel', 'Your ID', 'An offering for the altar'],
    placeholder: 'e.g. A warm layer and your sense of wonder' },
  { id: 'food', icon: '🍽️', label: 'Food & drink', type: 'chips',
    options: ['Dinner included', 'Snacks provided', 'Potluck', 'Drinks provided', 'Eat beforehand', 'Dessert on me'],
    placeholder: 'e.g. Three courses + mulled cider' },
  { id: 'cost', icon: '💸', label: 'Cost', type: 'chips',
    options: ['My treat ✨', 'Let’s split it', 'Totally free', 'Tickets are covered'],
    placeholder: 'e.g. About $20 each' },
  { id: 'transport', icon: '🚗', label: 'Getting there', type: 'chips',
    options: ['I’ll pick you up', 'Meet me there', 'Let’s ride together', 'Rideshare’s on me', 'Walking distance'],
    placeholder: 'e.g. I’ll pick you up at 6:30' },
  { id: 'parking', icon: '🅿️', label: 'Parking', type: 'chips',
    options: ['Free lot on site', 'Street parking', 'Valet', 'Skip the car'],
    placeholder: 'e.g. Free lot behind the building' },
  { id: 'weather', icon: '🌦️', label: 'Weather & terrain', type: 'chips',
    options: ['Indoors', 'Mostly outdoors', 'Might get muddy', 'Could be chilly — bring layers', 'Sunny — bring shades'],
    placeholder: 'e.g. Outdoors by the fire — it gets cold' },
  { id: 'activity', icon: '🥾', label: 'Activity level', type: 'chips',
    options: ['Totally chill', 'A little walking', 'Moderate', 'Active — wear sneakers'] },
  { id: 'vibe', icon: '✨', label: 'The vibe', type: 'chips',
    options: ['Low-key', 'Romantic', 'Playful', 'Fancy', 'Spooky', 'Adventurous', 'Witchy'] },
  { id: 'surprise', icon: '🎁', label: 'Surprise level', type: 'chips',
    options: ['No surprises', 'A little mystery', 'Total surprise — trust me'] },
  { id: 'guests', icon: '👯', label: 'Who’s coming', type: 'chips',
    options: ['Just us two', 'Bring a friend', 'Small group', 'Bring the whole coven'] },
  { id: 'kidspets', icon: '🐾', label: 'Kids & pets', type: 'chips',
    options: ['Pet-friendly', 'Kid-friendly', 'Adults only'] },
  { id: 'access', icon: '♿', label: 'Accessibility', type: 'text',
    placeholder: 'e.g. Step-free entrance, plenty of seating' },
  { id: 'link', icon: '🔗', label: 'Link', type: 'link',
    placeholder: 'https://… (tickets, menu, playlist)' },
  { id: 'notes', icon: '📝', label: 'Good to know', type: 'textarea',
    placeholder: 'Anything else — the secret password, which door, etc.' },
  { id: 'rsvpby', icon: '⏳', label: 'Please reply by', type: 'date' },
];
export const MODULE_BY_ID = Object.fromEntries(MODULES.map(m => [m.id, m]));

export const QUESTIONS = [
  { id: 'diet', q: 'Any allergies or food preferences?' },
  { id: 'drink', q: 'Drink of choice?' },
  { id: 'song', q: 'A song request for the night?' },
  { id: 'pickup', q: 'Where should I pick you up?' },
  { id: 'wish', q: 'Anything that would make it perfect?' },
];
export const QUESTION_BY_ID = Object.fromEntries(QUESTIONS.map(q => [q.id, q]));

export const TEMPLATES = [
  { id: 'dinner', icon: '🍷', label: 'Dinner date', title: 'Dinner for two', theme: 'candlelit',
    mods: { dress: 'Smart casual', cost: 'My treat ✨', transport: 'I’ll pick you up', vibe: 'Romantic' }, asks: ['diet'] },
  { id: 'picnic', icon: '🧺', label: 'Picnic', title: 'A picnic in the park', theme: 'picnic',
    mods: { dress: 'Comfy & cozy', bring: 'Just yourself', food: 'Snacks provided', weather: 'Mostly outdoors' }, asks: ['diet', 'drink'] },
  { id: 'stars', icon: '🔭', label: 'Stargazing', title: 'A night under the stars', theme: 'starlit',
    mods: { dress: 'Comfy & cozy', bring: 'A warm layer', weather: 'Could be chilly — bring layers', activity: 'Totally chill' }, asks: ['drink'] },
  { id: 'adventure', icon: '🥾', label: 'Adventure', title: 'An adventure awaits', theme: 'adventure',
    mods: { dress: 'Outdoor-ready', bring: 'Water bottle', activity: 'Moderate', weather: 'Might get muddy' }, asks: [] },
  { id: 'cozy', icon: '🍿', label: 'Movie night', title: 'Movie night in', theme: 'cozy',
    mods: { dress: 'Comfy & cozy', food: 'Snacks provided', vibe: 'Low-key' }, asks: ['drink', 'wish'] },
  { id: 'show', icon: '🎭', label: 'Show / concert', title: 'A night at the show', theme: 'show',
    mods: { dress: 'Dressy', cost: 'Tickets are covered', transport: 'Let’s ride together', link: { l: 'Our tickets', u: '' } }, asks: [] },
  { id: 'party', icon: '🎉', label: 'Party', title: 'You’re invited to celebrate!', theme: 'party',
    mods: { guests: 'Bring a friend', bring: 'Just yourself', dress: 'Wear something you love' }, asks: ['song'] },
  { id: 'sabbat', icon: '🕯️', label: 'Sabbat gathering', title: 'Gather for the turning of the wheel', theme: 'auto',
    mods: { bring: 'A dish to share', dress: 'Wear something you love', vibe: 'Witchy', guests: 'Small group' }, asks: ['diet'] },
  { id: 'coffee', icon: '☕', label: 'Coffee date', title: 'Coffee & conversation', theme: 'cozy',
    mods: { cost: 'My treat ✨', vibe: 'Low-key' }, asks: [] },
  { id: 'beach', icon: '🌊', label: 'Beach day', title: 'A day by the sea', theme: 'seaside',
    mods: { bring: 'Swimsuit & towel', weather: 'Sunny — bring shades', food: 'Snacks provided' }, asks: [] },
  { id: 'fae', icon: '🍄', label: 'Fairy-tale outing', title: 'Into the enchanted wood', theme: 'enchanted',
    mods: { dress: 'Costume encouraged', vibe: 'Playful', activity: 'A little walking' }, asks: [] },
  { id: 'surprise', icon: '🎁', label: 'Surprise', title: 'A surprise outing', theme: 'auto',
    mods: { surprise: 'Total surprise — trust me', dress: 'Smart casual' }, asks: ['pickup'] },
  { id: 'custom', icon: '✨', label: 'Something else', title: '', theme: 'auto', mods: {}, asks: [] },
];
