// Measures every drawn seal emblem in a real browser and writes EMBLEM_FIT in
// js/seal.js: the scale and center that put each emblem inside the seal's
// pressed face, clear of the raised ring. Run after adding or changing an
// emblem:  node scripts/fit-emblems.mjs   (the browser test checks it).
import { chromium } from '@playwright/test';
import { readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

export const FACE_REACH = 24.5; // the face is r=31.6; the rest is a margin of plain wax

// Renders emblem markup in a 100×100 box and finds its painted extent.
export async function measure(page, arts) {
  return page.evaluate(async arts => {
    const S = 400, out = {};
    for (const [id, art] of Object.entries(arts)) {
      const img = new Image();
      img.src = 'data:image/svg+xml,' + encodeURIComponent(`<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100' width='${S}' height='${S}'><g fill='#fff'>${art}</g></svg>`);
      await img.decode();
      const c = Object.assign(document.createElement('canvas'), { width: S, height: S });
      const g = c.getContext('2d');
      g.drawImage(img, 0, 0);
      const d = g.getImageData(0, 0, S, S).data;
      let x0 = S, y0 = S, x1 = 0, y1 = 0;
      const pts = [];
      for (let y = 0; y < S; y++) for (let x = 0; x < S; x++) if (d[(y * S + x) * 4 + 3] > 60) { pts.push(x, y); x0 = Math.min(x0, x); x1 = Math.max(x1, x); y0 = Math.min(y0, y); y1 = Math.max(y1, y); }
      const cx = (x0 + x1 + 1) / 2, cy = (y0 + y1 + 1) / 2;
      let r = 0, reach = 0;
      for (let i = 0; i < pts.length; i += 2) {
        const x = pts[i] + 0.5, y = pts[i + 1] + 0.5;
        r = Math.max(r, Math.hypot(x - cx, y - cy));
        reach = Math.max(reach, Math.hypot(x - S / 2, y - S / 2));
      }
      out[id] = { cx: cx / 4, cy: cy / 4, r: r / 4, reach: reach / 4 };
    }
    return out;
  }, arts);
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { SVG_EMBLEMS } = await import('../js/seal.js');
  const browser = await chromium.launch();
  const page = await browser.newPage();
  const m = await measure(page, SVG_EMBLEMS);
  await browser.close();
  const rows = Object.entries(m).map(([id, { cx, cy, r }]) => `  ${/^\w+$/.test(id) ? id : `'${id}'`}: [${(FACE_REACH / r).toFixed(3)}, ${cx.toFixed(1)}, ${cy.toFixed(1)}],`);
  const file = new URL('../js/seal.js', import.meta.url);
  const src = readFileSync(file, 'utf8');
  const block = `// EMBLEM_FIT:start (generated by scripts/fit-emblems.mjs — don't edit by hand)\nexport const EMBLEM_FIT = {\n${rows.join('\n')}\n};\n// EMBLEM_FIT:end`;
  const next = /\/\/ EMBLEM_FIT:start[\s\S]*?\/\/ EMBLEM_FIT:end/.test(src)
    ? src.replace(/\/\/ EMBLEM_FIT:start[\s\S]*?\/\/ EMBLEM_FIT:end/, block)
    : src.replace('// The picker, grouped.', `${block}\n\n// The picker, grouped.`);
  writeFileSync(file, next);
  console.log(`Fitted ${rows.length} emblems inside r=${FACE_REACH}.`);
}
